# CONFIGURACIÓN DEL SERVIDOR
server.port=8080

# CONFIGURACIÓN BASE DE DATOS ORACLE 
spring.datasource.url=jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=gacb052b0e9cc83_dbcursos_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
spring.datasource.username=ADMIN
spring.datasource.password=Duoc_2026_inscripciones
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

# RUTA PARA EL WALLET DENTRO DEL CONTENEDOR DOCKER
oracle.net.tns_admin=/app/OracleWallet

# SEGURIDAD: OAUTH2 RESOURCE SERVER (AZURE AD B2C)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cristianolivaresapi.b2clogin.com/cristianolivaresapi.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_signup_signin

# CONFIGURACIÓN AWS S3
# Ahora el SDK buscará automáticamente en /root/.aws/credentials
aws.s3.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:duoc-inscripciones-bucket-cristian-olivares}

# CONFIGURACIÓN RABBITMQ (MENSAJERÍA ASÍNCRONA)
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.connection-timeout=5000